name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]  # Change to 'main' if your default branch is named 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Use latest patch of Ruby 3.2
          bundler-cache: true
          cache-version: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose a stable version of Node.js

      - name: Install npm dependencies
        run: npm install  # Install PostCSS and other npm packages

      - name: Build with Jekyll
        run: |
          npm run build:css  # Run PostCSS build (adjust if you have a different script)
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
